name: Metrics
on:
  # Schedule updates (every day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_notable: yes
          plugin_notable_indepth: yes   
